# Generated by Django 2.0.6 on 2018-09-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_disciplina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplinaofertada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.TextField(max_length=255)),
                ('turma', models.TextField(max_length=5)),
                ('ano', models.TextField()),
                ('semestre', models.IntegerField()),
                ('professor', models.IntegerField()),
                ('disciplina', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='ementa',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='nome',
            field=models.TextField(max_length=50),
        ),
    ]
